[project]
name = "feeling-blue"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "atproto>=0.0.55",
    "fastapi>=0.115.5",
    "sqlmodel>=0.0.22",
]
